### ISSUE TITLE
Incorrect document link

### ISSUE THREAD

**Issue by Foeg** [petercorke/robotics-toolbox-python#146]
https://github.com/petercorke/robotics-toolbox-python/wiki/Models page contains a link in the text:

"ETS model, defined using a sequence of elementary transformations (rotation and translations), and is a quick and intuitive way to describe a robot, see this article. These models live in the folder roboticstoolbox/models/ETS."

The link appears to be incorrect - it refers to 'a-simple-and-systematic-approach-to-assigning-denavit-hartenberg-parameters'.   Which I believe is unrelated to the ETS topic.

**Comment by petercorke** [comment]
This project is still in the active development phase, so things still lack consistency and polish.  However the cited paper is definitely all about ETS.
