### ISSUE TITLE
Displaying multiple coordinate frames together created by trplot

### ISSUE THREAD

**Issue by rojas70** [petercorke/robotics-toolbox-python#149]
Greetings,

I am trying to use `trplot2` and `trplot`. The goal is to plot multiple coordinate frames within the same axes. 

Using `trplot` twice independently as shown below won't achieve this. 
```
T1 = transl2(1, 2)
T2 = transl2(2, 1)
plt.axes(xlim=(-1,4), ylim=(-1,4)) # is this the best way to adjust the axes?
trplot2(T1, frame='1', color='blue')
trplot2(T2, frame='2', color='red')
```
If I set `block=False` and use plt.show() I can achieve this... 
```
import matplotlib.pyplot as plt
T3=T1@T2
trplot2(T1, frame='3', color='red',block=False)
trplot2(T2, frame='3', color='green',block=False)
trplot2(T3, frame='3', color='blue',block=False)
plt.show()
```
If I close the window and simply call `plt.show()` once again, I cannot get the plot to show. I can fix this by placing a `fig = plt.figure()` at the beginning and calling `fig.show()' after I close and seeing it again.

```
fig = plt.figure()`
T1 = transl2(1, 2)
T2 = transl2(2, 1)
trplot2(T1, frame='3', color='red',block=False)
trplot2(T2, frame='3', color='green',block=False)
plt.show()
#close 
fig.show()
```

However, if I then call the following code and want to superimpose it, I cannot get it... So, it is not easy to get the behavior we get with matlab...
```
T3=T1@T2
trplot2(T3, frame='3', color='blue',block=False)
```
Any suggestions on how to permanently hold the figures?

**Comment by petercorke** [comment]
matplotlib graphics works quite differently to MATLAB.  If you run `plt.ion()` first, the plots are shown as you add them.  This is assuming you are working at the console.

```
>>> import matplotlib.pyplot as plt
>>> from spatialmath.base import transl2, trplot2
>>> T1 = transl2(1, 2)
>>> T2 = transl2(2, 1)
>>> T3=T1@T2
>>> plt.ion()
>>> trplot2(T1, frame='3', color='red',block=False)
<matplotlib.axes._subplots.AxesSubplot object at 0x7ff7507e9af0>
>>> trplot2(T2, frame='3', color='green',block=False)
<matplotlib.axes._subplots.AxesSubplot object at 0x7ff7507e9af0>
>>> trplot2(T3, frame='3', color='blue',block=False)
<matplotlib.axes._subplots.AxesSubplot object at 0x7ff7507e9af0>
```
