### ISSUE TITLE
How do we draw a point?

### ISSUE THREAD

**Issue by rojas70** [petercorke/robotics-toolbox-python#150]
I am trying to re-implement the functionality of:
````
plot_point(P, 'label', ' P', 'textcolor', 'k', 'solid', 'ko')
````
From the original matlab toolbox. I don't see any similar function to replicate this method. 
Any ideas?

**Comment by petercorke** [comment]
it might be more appropriate as part of the SpatialMath Toolbox, which also has the ability to draw coordinate frames

**Comment by rojas70** [comment]
It has yet to exist is it correct?

**Comment by petercorke** [comment]
This is now part of spatialmath, `base.plot_point()`
