### ISSUE TITLE
Visual servoing

### ISSUE THREAD

**Issue by ghx0x0** [petercorke/robotics-toolbox-python#152]
hello， 
       Does this python-toolbox support Visual servoing?   Or will you add it later?  I have used the robotics-toolbox-matlab before,  the visual servoing module is really perfect.
       Thanks.

**Comment by petercorke** [comment]
The plan is to add that functionality, but realistically it is months away.  Just as for the MATLAB case I am not sure if they should live in Robotics or Vision Toolbox.  What do you think?

**Comment by ghx0x0** [comment]
Thanks for ur reply.  I think Robotics Toolbox is better,  even though I know you put it in vision toolbox in matlab version :)
  I think  visual servoing technology is much more related to robotics.  :)
