### ISSUE TITLE
AttributeError: 'Panda' object has no attribute 'reach'

### ISSUE THREAD

**Issue by suddrey-qut** [petercorke/robotics-toolbox-python#156]
Solving the IK problem for the Panda robot results in the error ```AttributeError: 'Panda' object has no attribute 'reach'```.

The package was installed using the following commands:
```sh
git clone https://github.com/petercorke/robotics-toolbox-python.git
cd robotics-toolbox-python/
pip3 install -e .
```
Below is the code which resulted in the error:
```python3
import roboticstoolbox as rtb
from spatialmath import SE3

robot = rtb.models.URDF.Panda()

env = rtb.backends.Swift()  # instantiate 3D browser-based visualizer
env.launch()                # activate it
env.add(robot)  

T = SE3(0.8, 0.2, 0.1) * SE3.OA([0, 1, 0], [0, 0, -1])
q_pickup, *_ = robot.ikunc(T)
```

Thank you.

**Comment by petercorke** [comment]
This is fixed.  Note that the IK functions are now systematically named, this one is now ikine_unc().  While it does converge and declare "success" it is not very accurate, that's currently under investigation. Some info about IK solvers now available here https://github.com/petercorke/robotics-toolbox-python/wiki/Kinematics
