### ISSUE TITLE
Issues with Example Code

### ISSUE THREAD

**Issue by kleibrandt** [petercorke/robotics-toolbox-python#162]
It seems there is an issue with (using python 3.9 with spatialmath_python-0.8.5-py3.9) :
    `examples/puma_fdyn.py`
    
 I had to change in `Robot.py`:
 ```
     def _plot_pyplot(
        ...
        q = getmatrix(q.T, (q.shape[1], self.n)) # was: q = getmatrix(q, (None, self.n))
        
 ```
 
 However, I'm not sure that this is the correct syntax, since `q = getmatrix(q, (None, self.n))` is used in multiple places in `Robot.py`
 
 Also the code in the readme (cover page), seems to use the wrong syntax, I believe:
 ```
 qt = rtb.trajectory.jtraj(robot.qz, q_pickup, 50)
robot.plot(qt.q, movie='panda1.gif')
 ```
 
needs to be changed to:
 ```
qt = rtb.tools.trajectory.jtraj(robot.qz, q_pickup, 50)
robot.plot(qt.q.T, movie='panda1.gif')
 ```

**Comment by petercorke** [comment]
Trajectories are meant to be MxN matrices where N is number of joints.  This is as it was in the MATLAB version, but it was initially implemented as NxM, and we're trying to fix all instances.  This example was overlooked, so just remove the .T from it, and you are all good.
