### ISSUE TITLE
How to draw multiple robots in the same figure

### ISSUE THREAD

**Issue by TrenywanG** [petercorke/robotics-toolbox-python#163]
I am trying to draw multiple poses of a robot in the same figure and also need to represent SE3 in it.
How can I do this, plz?

**Comment by petercorke** [comment]
The backend should be able to handle this, see scratchy documentation on the wiki

https://github.com/petercorke/robotics-toolbox-python/wiki/Backends

* instantiate a backend
* repeat 
  *   instantiate a robot
  * add it to the backend, set its configuration
* step the environment

**Comment by TrenywanG** [comment]
Thank you for your answer
