### ISSUE TITLE
Error in End Effector Calculation of Panda 

### ISSUE THREAD

**Issue by momo1901** [petercorke/robotics-toolbox-python#165]
Hi,

While calculating the end-effector position of the Franka Emika Panda robot in VREP, using the toolbox, the tip position is showing at the wrong position.

In the below image, the toolbox calculates the end-effector position wrongly. I am unaware as to what is the reason for this, but this also impacts the inverse kinematics ahead as well. As you can see that the actual tip position shown using the tip dummy is different than the one calculated by the toolbox.

![error in end](https://user-images.githubusercontent.com/43992747/104272060-9799c300-549c-11eb-8d87-bf097515bea6.png)

The below 2 images also show that when the tip position is moved to the position calculated by the toolbox, the position is at the wrong location especially in the Y and X axis.
![error_3](https://user-images.githubusercontent.com/43992747/104272861-56a2ae00-549e-11eb-9c7a-6cefa70a375d.png)

![error_2](https://user-images.githubusercontent.com/43992747/104272865-586c7180-549e-11eb-914a-7143e170d534.png)

I would request if to help me out in removing this error or mistake asap, as it's affecting other calculations ahead.

Thanks.

**Comment by petercorke** [comment]
Could you send the joint configuration vector, with full precision, ie. lots of digits, and the SE3 matrix from vrep
