### ISSUE TITLE
 Building wheel for roboticstoolbox-python (setup.py) ... error

### ISSUE THREAD

**Issue by Kanglatae** [petercorke/robotics-toolbox-python#169]
![Screenshot 2021-02-01 143715](https://user-images.githubusercontent.com/71601955/106427060-a6730480-64a1-11eb-884c-4404c228381d.png)
![Screenshot 2021-02-01 143758](https://user-images.githubusercontent.com/71601955/106427075-abd04f00-64a1-11eb-98df-5bf187d4dbd8.png)
![Screenshot 2021-02-01 143852](https://user-images.githubusercontent.com/71601955/106427078-ae32a900-64a1-11eb-817c-b89213f898db.png)
![Screenshot 2021-02-01 143928](https://user-images.githubusercontent.com/71601955/106427080-b0950300-64a1-11eb-922b-43a5111a59c2.png)
![Screenshot 2021-02-01 144022](https://user-images.githubusercontent.com/71601955/106427084-b38ff380-64a1-11eb-84d5-fe19f8d0defb.png)
![Screenshot 2021-02-01 144043](https://user-images.githubusercontent.com/71601955/106427087-b559b700-64a1-11eb-882a-ea86ccb1edbb.png)
![Screenshot 2021-02-01 144133](https://user-images.githubusercontent.com/71601955/106427091-b7237a80-64a1-11eb-8191-d211a62a3a9a.png)
![Screenshot 2021-02-01 144154](https://user-images.githubusercontent.com/71601955/106427095-b8ed3e00-64a1-11eb-8559-63d5bcf20f85.png)
![Screenshot 2021-02-01 144221](https://user-images.githubusercontent.com/71601955/106427100-bab70180-64a1-11eb-8158-16bc0e229d87.png)
![Screenshot 2021-02-01 144253](https://user-images.githubusercontent.com/71601955/106427106-bc80c500-64a1-11eb-8ee3-51f126379b2a.png)

**Comment by Jakubach** [comment]
I had the same error and I fixed it by installing from source with command:
`pip3 install git+https://github.com/petercorke/robotics-toolbox-python`

**Comment by Kanglatae** [comment]
> I had the same error and I fixed it by installing from source with command:
> `pip3 install git+https://github.com/petercorke/robotics-toolbox-python`

Worked. Thank you!

**Comment by petercorke** [comment]
What platform?

**Comment by Kanglatae** [comment]
> What platform?

Windows.

**Comment by petercorke** [comment]
Fixed now.  For some reason your install was building locally, even though we ship a wheel for Windows.  There was a missing .h file in the package which is why you got the error.

**Comment by jhavl** [comment]
This was fixed with v0.8.0 which has been pushed to PyPI. Extra files were not being included in the source dist.

**Comment by MCollins52** [comment]
I'm running into the same (or very similar) issue. I tried installing from source which is mentioned above but no luck. I'm on Windows 10 with Python 3.9. Any help?

**Comment by jhavl** [comment]
Can you please attach the error output?

**Comment by MCollins52** [comment]
> Can you please attach the error output?

![1](https://user-images.githubusercontent.com/57005956/114633699-08fd3380-9c8f-11eb-81cf-c5bb5690c17a.png)
![2](https://user-images.githubusercontent.com/57005956/114633701-08fd3380-9c8f-11eb-96e7-fd57a860db4f.png)
![3](https://user-images.githubusercontent.com/57005956/114633702-08fd3380-9c8f-11eb-93dd-f00a6d902d84.png)
![4](https://user-images.githubusercontent.com/57005956/114633703-0995ca00-9c8f-11eb-8801-9d9e6cead569.png)
![5](https://user-images.githubusercontent.com/57005956/114633704-0995ca00-9c8f-11eb-868a-1c48f4d93cb2.png)
![6](https://user-images.githubusercontent.com/57005956/114633705-0995ca00-9c8f-11eb-819c-5e0b8f4463fd.png)
![7](https://user-images.githubusercontent.com/57005956/114633706-0995ca00-9c8f-11eb-8354-36ec92480166.png)
![8](https://user-images.githubusercontent.com/57005956/114633707-0a2e6080-9c8f-11eb-8548-1af5e3e12a9f.png)

**Comment by jhavl** [comment]
Thanks for that. This is a different issue to the one above. It seems that the build tools can't locate the standard library math.h. This issue should be fixable by re-installing the C++ build tools which can be downloaded [here](https://visualstudio.microsoft.com/visual-cpp-build-tools/).

Otherwise, the PyPI version of the toolbox is pre-build so not build tools are required. We will be pushing a new version of the toolbox to PypI this week so it will be up to date.

**Comment by MCollins52** [comment]
> Thanks for that. This is a different issue to the one above. It seems that the build tools can't locate the standard library math.h. This issue should be fixable by re-installing the C++ build tools which can be downloaded [here](https://visualstudio.microsoft.com/visual-cpp-build-tools/).
> 
> Otherwise, the PyPI version of the toolbox is pre-build so not build tools are required. We will be pushing a new version of the toolbox to PypI this week so it will be up to date.

I installed the build tools and that didn't seem to work, so I updated the C++ build tools that I currently had installed and installed the toolbox using pip, and that seemed to work. Thanks!
