### ISSUE TITLE
Elbow-up/elbow-down configuration issue

### ISSUE THREAD

**Issue by Jakubach** [petercorke/robotics-toolbox-python#171]
Hello,
I am testing on Windows 10 the Puma560 robot.
Plotting puma's qn position I get elbow-up configuration:
```
import roboticstoolbox as rtb
robot = rtb.models.DH.Puma560()
robot.plot(robot.qn)
```
![puma_elbow_up](https://user-images.githubusercontent.com/29859041/106893539-fd6d1980-66ed-11eb-824d-7e51087d4c0c.png)
qn: [0.         0.78539816 3.14159265 0.         0.78539816 0.        ]
Then, I solve forward kinematics to get transformation matrix.
`T = robot.fkine(robot.qn)`
And solve inverse kinematics for the same position and orientation but with another configuration (elbow-down):
`qd = robot.ikine_a(T = T, config="rd")`
But resulting configuration is still elbow-up.
qd: [-2.77555756e-17  7.85398163e-01  3.14159265e+00  3.14159265e+00
 -7.85398163e-01 -3.14159265e+00]
Changing to `qd = robot.ikine_a(T = T, config="ru")` which should result in elbow-up configuration gives me elbow-down config.
qd:[-2.77555756e-17 -8.33533063e-01  9.39558327e-02  1.05479583e-17
 -8.31219097e-01 -5.23446762e-17]

**Comment by petercorke** [comment]
Thanks for letting me know.   The MATLAB code does this as well, which means the port is accurate :)  I know the MATLAB code used to get this right, so it'll take me a while to get to the bottom of.  This is amongst some of the oldest code in RTB...

**Comment by petercorke** [comment]
Fixed on GH.
