### ISSUE TITLE
ikine_LMS doesn't work for URDF (ERobot) models

### ISSUE THREAD

**Issue by dd-ff** [petercorke/robotics-toolbox-python#174]
When trying to calculate inverse kinematics using LMS or LM variant using official (implemented) URDF robot or a personal one, an error is thrown in this manner:

...\roboticstoolbox\robot\IK.py", line 534, in ikine_LMS
     k = np.logical_and(q > np.pi, revolutes)
ValueError: operands could not be broadcast together with shapes (7,) (9,)

In order to test it you could simply use following script:

robot = rtb.models.URDF.Panda()
T = SE3()
sol = robot.ikine_LMS(T)

**Comment by jhavl** [comment]
Thanks for bringing this to our attention, this should be fixed now.

**Comment by dd-ff** [comment]
Great, 
Now you can do the same fix for ikine_LM. :-)
