### ISSUE TITLE
Puma560 wrong configuration in Swift

### ISSUE THREAD

**Issue by BartlomiejKulecki** [petercorke/robotics-toolbox-python#183]
Hello,
when I plot puma in config qn in swift it has different configuration than in matplotlib. Here is the code:
```
import roboticstoolbox as rtb
# pyplot
robot = rtb.models.DH.Puma560()
robot.plot(q=robot.qn)
# swift
robot = rtb.models.Puma560()
robot.plot(q=robot.qn)
```
And results:
<img src="https://user-images.githubusercontent.com/37365394/109148896-1f930e00-7767-11eb-9663-bf71f3fb953f.png" alt="puma_plot" height=300/> |  <img src="https://user-images.githubusercontent.com/37365394/109148899-20c43b00-7767-11eb-820e-b1aade094d91.png" alt="puma_swift" height=300/>

**Comment by petercorke** [comment]
This is not so much a Swift issue as a URDF model issue.  The kinematic conventions of the model are whatever is baked into that URDF file which comes from ROS land. The kinematic models of each can be seen by print() 'ing them. On a quick look there is a 180 deg difference in elbow rotation, but there might be others.

There is no Puma standard.  Each model is its own truth.
