### ISSUE TITLE
base\__init__.py missing serial_link import

### ISSUE THREAD

**Issue by shermama96** [petercorke/robotics-toolbox-python#19]
The import statement "robopy.base.serial_link" is missing from robopy\base\__init__.py so different classes inside serial_link are unresolved when importing robopy to to a script.

Is;
from robopy.base.transforms import *
from robopy.base.model import *
from robopy.base.quaternion import *
from robopy.base.pose import *
from robopy.base.util import *

S/B:
from robopy.base.transforms import *
from robopy.base.model import *
from robopy.base.quaternion import *
from robopy.base.pose import *
from robopy.base.util import *
from robopy.base.serial_link import *

**Comment by petercorke** [comment]
Hi,

this is an old project that is coming back to life so the code base will be a bit unstable for the rest of the year.

peter
