### ISSUE TITLE
Printing symbolic equations

### ISSUE THREAD

**Issue by Jakubach** [petercorke/robotics-toolbox-python#195]
Hello,
I noticed that matrices with long symbolic equations are printed very shrink.
I found my own priting method and I suggest to align them by the longest term like this:
```
def print_SE3(SE3_matrix : SE3):
    SE3_numpy = SE3_matrix.A
    max_item_length = SE3_numpy.astype(np.string_).dtype.itemsize
    with np.printoptions(precision=3, suppress=True, linewidth = np.inf, formatter = {'all':lambda x: f"{str(x):{max_item_length}}"}):
        print(SE3_numpy)
```

**Comment by jhavl** [comment]
This belongs to the spatialmath-python package. Feel free to re-make an issue on that github page if desired
