### ISSUE TITLE
Swift backend using old spatialmath function

### ISSUE THREAD

**Issue by adv4ncr** [petercorke/robotics-toolbox-python#206]
Hi there,
I just found a minor bug in the following line:

https://github.com/petercorke/robotics-toolbox-python/blob/d531939f9571f58662fd3265971b13c696a7e639/roboticstoolbox/backends/Swift/Swift.py#L481

It should be `shape.base = sm.SE3.Rt(R, t=t)`, if I am not mistaken.

Great work with the toolbox so far 😃 
Yours, Vinc

**Comment by adv4ncr** [comment]
swift was extracted from this repo

**Comment by jhavl** [comment]
Thanks for the heads up. This is still not properly resoved in Swift so I'll fix it shortly.
