### ISSUE TITLE
'Mesh' object has no attribute '_sq'

### ISSUE THREAD

**Issue by oridong** [petercorke/robotics-toolbox-python#220]
win10 python3.8.9

'Mesh' object has no attribute '_sq'

error parsing URDF file D:\0ws_python\0MyPackages\rtb_data-0.9.1-py3.8\rtbdata\xacro\franka_description\robots\panda_arm_hand.urdf.xacro

**Comment by Giessen** [comment]
Same problem here....

**Comment by jhavl** [comment]
Try doing `pip install -U spatialgeometry` and check out [common issues](https://github.com/petercorke/robotics-toolbox-python/wiki/Common-Issues) too see if any points there help

**Comment by Giessen** [comment]
I try uninstall spatialgeometry and reinstall from source, it works! Thanks

**Comment by oridong** [comment]
> I try uninstall spatialgeometry and reinstall from source, it works! Thanks
first I uninstalled spatialgeometry.
I dowload it from https://github.com/jhavl/spatialgeometry, and python setup.py install , but the problem still exists.
Then  I  uninstalled spatialgeometry and `pip install -U spatialgeometry` , but the problem also exists.
How did you do ?

**Comment by jhavl** [comment]
If you do `pip list` what version of spatialgeometry do you see?

**Comment by oridong** [comment]
> If you do `pip list` what version of spatialgeometry do you see?
roboticstoolbox-python 0.9.1
spatialgeometry        0.1.0
spatialmath-python     0.9.6

**Comment by jhavl** [comment]
spatialgeometry should have been v0.1.1. The PyPI release from yesterday didn't work properly so your `pip install -U spatialgeometry` didn't update anything. I've just re-released it with version 0.1.2 and so now if you do `pip install -U spatialgeometry` you should end up with version 0.1.2 and everything will work.

**Comment by oridong** [comment]
> spatialgeometry should have been v0.1.1. The PyPI release from yesterday didn't work properly so your `pip install -U spatialgeometry` didn't update anything. I've just re-released it with version 0.1.2 and so now if you do `pip install -U spatialgeometry` you should end up with version 0.1.2 and everything will work.

Ok, this problem is solved.
