### ISSUE TITLE
run the github version of examples/vehicle1.py, it said file greycar.png can't be found

### ISSUE THREAD

**Issue by asmwarrior** [petercorke/robotics-toolbox-python#223]
Hi, I'm using the github version of both `robotics-toolbox-python`, `spatialgeometry`, `spatialmath-python`, `swift`.

Now, run the code `examples/vehicle1.py`, I got such error:

~~~~
In [1]: runfile('E:/code/robotics/robotics-toolbox-python/roboticstoolbox/examples/vehicle1.py', wdir='E:/code/robotics/robotics-toolbox-python/roboticstoolbox/examples')
Traceback (most recent call last):

  File "E:\code\robotics\robotics-toolbox-python\roboticstoolbox\examples\vehicle1.py", line 8, in <module>
    anim = VehicleIcon('greycar', scale=2)

  File "e:\code\robotics\robotics-toolbox-python\roboticstoolbox\mobile\animations.py", line 244, in __init__
    image = loaddata(filename + ".png", plt.imread)

  File "e:\code\robotics\robotics-toolbox-python\roboticstoolbox\tools\data.py", line 53, in loaddata
    path = path_to_datafile(filename)

  File "e:\code\robotics\robotics-toolbox-python\roboticstoolbox\tools\data.py", line 102, in path_to_datafile
    raise ValueError(f"file {filename} not found locally or in rtbdata")

ValueError: file greycar.png not found locally or in rtbdata


In [2]: 
~~~~

I just found this png file is located in this folder
`E:\code\robotics\robotics-toolbox-python\rtb-data\rtbdata\data\greycar.png`

So, if I copy this `greycar.png` to the same folder as the `vehicle1.py` file locates, I don't get such error now.

So, my guess is: do I have to add some python package named `rtbdata`?  What is the install steps?

Thanks.

**Comment by petercorke** [comment]
Mobile robotics is very embryonic, it will get a burst of love later next month.  Don't bother suggesting minor fixes, but if you want to take on a big chunk of work let me know
