### ISSUE TITLE
Some code is not correct in python_toolbox_icra_2020-5.pdf

### ISSUE THREAD

**Issue by asmwarrior** [petercorke/robotics-toolbox-python#225]
`https://petercorke.com/download/31/python-tools/1296/python_toolbox_icra_2020-5.pdf`

I see some code is not correct:

~~~~
q = sym.symbols("q_:6") # q = (q_1, q_2, ... q_5)
~~~~

I think it should be `symbols`, not `symbol` nor `Symbol`, at least only `symbols` works in my `WinPython 3.8.8.0`.

**Comment by petercorke** [comment]
It is correct as written
```
q = sym.symbol("q_:6") # q = (q_1, q_2, ... q_5
```

The first code line in the paper
```
from spatialmath.base import *
```
brings in the RTB sym module.
