### ISSUE TITLE
document issue in tools/p_servo.py

### ISSUE THREAD

**Issue by asmwarrior** [petercorke/robotics-toolbox-python#231]
https://github.com/petercorke/robotics-toolbox-python/blob/872ff3eb9b77bc832c3b315ee210a6dd1e4b8456/roboticstoolbox/tools/p_servo.py#L40-L47

I think the "velocity" is not correct here, should we remove it?
It should be "Translational error" and "Angular error".

Thanks.

**Comment by jhavl** [comment]
Thanks for picking that up!
