### ISSUE TITLE
AtrribuiteError when using the rne method in a robot with a custom base

### ISSUE THREAD

**Issue by juanjqo** [petercorke/robotics-toolbox-python#232]
**Check here first**

[Common issues](https://github.com/petercorke/robotics-toolbox-python/wiki/Common-Issues)

**Describe the bug**
Hi guys! 
The _rne_ method returns an error (AtrribuiteError) When I compute the torques using a custom robot with a base different from 'None' .

**Version information**

Did you install from PyPI or GitHub? PyPI
If PyPI what version number? 0.9.1
If GitHub what commit hash?

Robotics Toolbox depends heavily on two other packages: Swift (3D graphics) and SpatialMath toolbox (underpinning maths utilities).  If you think your issue is related to these, then please answer the questions above for them.

**To Reproduce**
I used a custom 3-DOF robot:

`import roboticstoolbox as rtb

import numpy as np
from math import pi
from scipy.linalg import block_diag

m = np.array([0.5, 0.5, 0.5])
I = np.zeros((3,3,3))
I[0, :, :] = np.array([[2.00000000e-02, -1.04749986e-09, -2.44450000e-09],
                       [-5.82000000e-10,  2.00000000e-02, -8.56591090e-17],
                       [-2.44450000e-09, -9.31500156e-10,  2.00000000e-02]])

I[1, :, :] = np.array([[2.00000000e-02,  2.21828307e-18, -4.08486407e-18],
                       [2.21829066e-18,  2.00000000e-02, -1.25014681e-18],
                       [-4.08486407e-18, -1.25014678e-18,  2.00000000e-02]])

I[2, :, :] = np.array([[2.00000000e-02, -1.05800084e-08,  1.04749986e-09],
                       [-9.65000844e-09,  2.00000000e-02,  9.31412730e-10],
                       [1.10599986e-09,  9.31404313e-10,  2.00000000e-02]])

r =  np.array([[1.06300101e-05, -3.89500000e-02,  1.15199999e-04],
               [2.05050000e-01, -3.16258847e-05,  2.32500000e-02],
               [1.49498294e-03, -2.39000013e-03, -8.32499996e-02]])
d = np.array([-0.1188,0,-0.0098,-0.252])
a = np.array([0,-0.41,0])
alpha = np.array([-pi/2, -pi, pi/2])
n = 3
l = [None] * n

Tbase = block_diag(1,1,1,1)

for i in range(n):
    l[i] = rtb.RevoluteDH(d=d[i], a=a[i], alpha=alpha[i], m=m[i],
                          r=np.array(r[i,:]),
                          I= I[i, :, :])
rtoolbox_robot = rtb.DHRobot(l, meshdir=None, base=Tbase)

dof = 3
q = np.random.rand(dof)
q_dot = np.random.rand(dof)
q_dot_dot = np.random.rand(dof)
tau = rtoolbox_robot .rne(q, q_dot, q_dot_dot)
print('torques', tau)`

Output:

> Traceback (most recent call last):
  File "/home/juanjqo/Documents/Poppeye_Repository/poppeye-ros/my_dynamixel_poppy/src/poppeye_rosPython/robot_dynamics/Rtoolbox_tests/minimal_example.py", line 44, in <module>
    tau = rtoolbox_robot .rne(q, q_dot, q_dot_dot)
  File "/home/juanjqo/.local/lib/python3.6/site-packages/roboticstoolbox/robot/DHLink.py", line 22, in wrapper_check_rne
    return func(*args, **kwargs)
  File "/home/juanjqo/.local/lib/python3.6/site-packages/roboticstoolbox/robot/DHRobot.py", line 1268, in rne
    gravity = self.base.R.T @ gravity
  File "/home/juanjqo/.local/lib/python3.6/site-packages/roboticstoolbox/robot/Robot.py", line 531, in base
    if self._base is None:
AttributeError: 'DHRobot' object has no attribute '_base'

**Expected behavior**
I expected the following torques:
> torques [ 0.00802459  3.02988668 -0.13686581]

Process finished with exit code 0

This result is obtained using the same code, but replacing the line 38: 
This is, by using

> rtoolbox_robot = rtb.DHRobot(l, meshdir=None, base=None)

 instead of

> rtoolbox_robot = rtb.DHRobot(l, meshdir=None, base=Tbase)

**Screenshots**

**Environment (please complete the following information):**
 - Your OS (MacOS, Linux, Windows). GNU/Linux (Ubuntu 18.04.5 LTS)
- Your Python version. 3.6.9

**Comment by petercorke** [comment]
0.9.1 needs to be updated, using the GH version I can do RNE on a DHRobot with a base transform
```
(rtb) >>> puma.base=SE3(1,2,3)

(rtb) >>> puma.rne(puma.qz,puma.qz,puma.qz)
Out[8]: array([       0,    37.48,   0.2489,        0,        0,        0])
```
We'll try and push a new version very soon.
