### ISSUE TITLE
Time vector for trajectories not a function of the path length

### ISSUE THREAD

**Issue by suddrey** [petercorke/robotics-toolbox-python#237]
The current joint trajectory function requires that you pass either a integer defining a fixed number of timesteps, or a linear vector of timesteps over which to scale the velocities/accelerations of the trajectory, seen below.

```py
def jtraj(q0, qf, t, qd0=None, qd1=None):
  """
  ...
  Notes:
    - The time vector, if given, scales the velocity and acceleration outputs
      assuming that the time vector starts at zero and increases
      linearly.
  """
```

However, the issue I forsee with this is that in the former case (integer number of timesteps), the velocities will scale by total distance travelled, rather than distance/time, meaning that a small rotation of the wrist, and a wide swing of the arm will take the same time, but will have wildly different velocities; and in the latter case, the maximum duration of the trajectory needs to be known/estimated prior to calculating the path, otherwise leading to a similar issue as the first case.

Would it be possible to add a non-time based scaling factor (e.g. maximum EE velocity), which is used to normalise the set of unscaled velocities as an additional option?

**Comment by petercorke** [comment]
What this saying, perhaps not well, is that a scalar `N` is the same as `range(N)`, and the returned velocity/acceleration are not in units of rad/s or rad/s2 but rather rad/step and rad/step^2.  

If you specify a vector of times, say `[0, dt, 2*dt, ... (N-1)*dt]` then the velocity and acceleration outputs are properly scaled to be rad/s and rad/s^2.

The joint coordinates in either case are exactly the same, `N` steps to get from `q0` to `qf`.

That said, there is probably a need to scale the motion duration to enforce limits, but would require some kind of weighting between rotational and translational motion required.  If the start and end are `SE3`s `T0` and `Tf` then `norm(T0.t - T1.t)` is the translational distance and `SO3(T0.R).angdist(SO3(T1.R))` is the rotation distance (I should do something to make that latter expression simpler)
