### ISSUE TITLE
Is it possible to draw a 3D lines(trajectory) in swift envirnment?

### ISSUE THREAD

**Issue by asmwarrior** [petercorke/robotics-toolbox-python#239]
Hi, I just want to draw the how 3D trajectory of the end-effector of an robot arm in swift environment. Is this possible?

I see that some 3D geometries such as box, sphere are already supported, but I'm not sure whether a 3D lines is possible.

Thanks.

**Comment by jhavl** [comment]
Hey @asmwarrior, it's not currently possible, but on the list of things to add

**Comment by jhavl** [comment]
This issue fits on the [Swift repo](https://github.com/jhavl/swift), so I'll close it here, happy for you to re-add as a Swift issue.
