### ISSUE TITLE
how to convert the SE3 array to numpy?

### ISSUE THREAD

**Issue by nexus1203** [petercorke/robotics-toolbox-python#246]
This is great library for working with the robotics simulation. But I am trying to save the output of the forward kinematics transform.
However I can't find a way to convert the SE3 output to the numpy array. Kindly advice how to do that.
Thanks a lot.

**Comment by petercorke** [comment]
Use `.A`

```
(rtb) >>> SE3.Rand().A
array([[  0.8854,  -0.4262,   0.1857,   0.2253],
       [ -0.3505,  -0.8744,  -0.3354,   0.2726],
       [  0.3053,   0.2319,  -0.9236,   0.8861],
       [       0,        0,        0,        1]])
```
