### ISSUE TITLE
Memory leak frne

### ISSUE THREAD

**Issue by ArthurEsquerrePourtere** [petercorke/robotics-toolbox-python#247]
Hello,
I have a memory leak coming  from the accel function when I run this code :

          import roboticstoolbox as rtb
          def getPlanarRobot2DOF():
          
                  # link 1
                  m1 = 1
                  l1 = 1
                  lc1 = 0.5
                  
                  # link 2
                  m2 = 1
                  l2 = 1
                  lc2 = 0.5
                  
                  L1 = rtb.RevoluteDH(a=l1, B=1, m=m1, r=[-lc1, 0, 0], G=1)
                  L2 = rtb.RevoluteDH(a=l2, B=1, m=m2, r=[-lc2, 0, 0], G=1)
                  return rtb.DHRobot([L1, L2], gravity=[0, 0, 0])
          
          robot=getPlanarRobot2DOF()
          for _ in range(1000):
              robot.accel([0,0], [0,0], [0,0])

The memory leak seems to come from the function frne [in this file](https://github.com/petercorke/robotics-toolbox-python/blob/master/roboticstoolbox/core/frne.c).

**Comment by jhavl** [comment]
Thanks for bringing this to our attention, this is now fixed on the `future` branch for the next release.
