### ISSUE TITLE
Unable to load custom URDF models from absolute paths

### ISSUE THREAD

**Issue by suddrey-qut** [petercorke/robotics-toolbox-python#258]
**Describe the bug**
Unable to load arbitrary urdf paths as toolbox restricts model loading to .local/ros and rtbdata package.

**Version information**

Did you install from PyPI or GitHub? PyPi
If PyPI what version number? 0.10.1

Robotics Toolbox depends heavily on two other packages: Swift (3D graphics) and SpatialMath toolbox (underpinning maths utilities).  If you think your issue is related to these, then please answer the questions above for them.

**To Reproduce**
1. The shortest, complete, Python script that exhibits the bug.
```python
links, name = self.URDF_read(
            "irb6700/robots/irb6700_200_260.xacro", tld='/absolute/path/to/resources'
        )
```
2. The script output, including error messages.
```
No such file or directory: /home/AAA/.local/lib/python3.8/site-packages/rtbdata/xacro/irb6700/robots/irb6700_200_260.xacro [Errno 2] No such file or directory: '/home/AAA/.local/lib/python3.8/site-packages/rtbdata/xacro/irb6700/robots/irb6700_200_260.xacro'
```
**Expected behavior**
The package should load resources relative to the provided tld

**Environment (please complete the following information):**
 - Your OS (MacOS, Linux, Windows). Linux
- Your Python version. 3.8.10

**Additional context**
I have managed to resolve this locally by making the following changes to rtb/tools/data.py

Adding the following lines:
```python
base_path = importlib.import_module("rtbdata").__path__[0]

def set_base_path(path):
    global base_path
    base_path = path
```

and changing path_to_datafile to use base_path instead of importlib.import_module("rtbdata").__path__[0]
```python
root = Path(base_path)
```

This allows me to do the following
```python
        old_base = data.base_path
        data.set_base_path(RosPack().get_path('armer_abb') + '/data')
        
        links, name = self.URDF_read(
            "irb6700/robots/irb6700_200_260.xacro"
        )

        data.set_base_path(old_base)
```

**Comment by jhavl** [comment]
This has been fixed on the future branch, have a look at [here](https://github.com/petercorke/robotics-toolbox-python/blob/future/tests/test_CustomXacro.py) for an example on loading a xacro from a custom destination.
