### ISSUE TITLE
not able to import box shape

### ISSUE THREAD

**Issue by prajwalresearch** [petercorke/robotics-toolbox-python#259]
Hi,everyone I have installed robotics-toolbox from github ( pip install -e .) method . 
Then I tried using this example [neo/box](https://github.com/jhavl/neo/blob/master/examples/bookshelf.py)
but I am getting 
AttributeError: module 'roboticstoolbox' has no attribute 'Box'
I am able to import shpere but not the box. any suggestions?

**Comment by jhavl** [comment]
Hey prajwalresearch, 
Apologies, this is an error on my part. Shapes have been moved to the [spatialgeometry package](https://github.com/jhavl/spatialgeometry) which does get installed by default with the toolbox. I'll update those examples today. A more up to date version is [here](https://github.com/petercorke/robotics-toolbox-python/blob/master/roboticstoolbox/examples/neo.py)

Quick example

```
import spatialgeometry as sg

box = sg.Box([0.1, 0.2, 0.3])
```

Note that in version 0.2.0 of spatialgeometry, the Box has been renamed to Cuboid
