### ISSUE TITLE
Inverse Kinematics solutions

### ISSUE THREAD

**Issue by prajwalresearch** [petercorke/robotics-toolbox-python#260]
Hello everyone , I don't know much about Ik . But I believe for 7dof franka panda arm I should be getting multiple IK solutions , provided I fixed both pos and orientation of end affector.
I am using robot.ikine but it's giving me only one same  Ik solution .any one knows how to get multiple IK solutions if exist any?

**Comment by jhavl** [comment]
Hey prajwalresearch, currently our IK methods will only return the first obtained solution, even though many may exist.  To get different solutions, you can try to run the IK method multiple times where q0 (the initial robot joint configuration) is randomised every time.
