### ISSUE TITLE
How to calculate roll, pitch, yaw angles?

### ISSUE THREAD

**Issue by BogwangKim** [petercorke/robotics-toolbox-python#271]
Hi I'm just starting out with kinematics using this tool.
I can only get angle values of 6 axes and x,y,z coordinates with fkine() and ikine_LMS().
Do I have to do the calculation manually with the output of fkine()?

**Comment by petercorke** [comment]
your question is not clear, can you try again

**Comment by BogwangKim** [comment]
It was a stupid question.
I should have read the documentation more carefully.
