### ISSUE TITLE
The red noodle-like mechanical linkage is always too short to be easy to observe！！！！！

### ISSUE THREAD

**Issue by w-1016-Papman** [petercorke/robotics-toolbox-python#274]
Hey bro

I want to know if the visualized red noodle-like model in roboticstoolbox-python can stretch it? Because every time the displayed model changes the scale according to the data I input, it will always automatically select a larger scale, which makes my model very small and difficult to observe

**Comment by jhavl** [comment]
You can clone the toolbox from github and modify any model you like to suit your needs. I'm not sure which model you are referring to but look in roboticstoolbox/models/ for this one and then you can adjust the links to be as long as you want.
