### ISSUE TITLE
No solution of inverse transformation when using the 'flip' parameter

### ISSUE THREAD

**Issue by jorks3z** [petercorke/robotics-toolbox-python#275]
**Check here first**

[Common issues](https://github.com/petercorke/robotics-toolbox-python/wiki/Common-Issues)

**Describe the bug**
If you use the parameter "flip" from the DHLink class, it is no longer possible to find a solution of the inverse transformation. 

**Version information**

Conda installation
roboticstoolbox-python    0.11.0           py39h5d4886f_0    conda-forge
rtb-data                             0.10.0           pyhd8ed1ab_0       conda-forge
scipy                     1.7.1            py39hc0c34ad_0    conda-forge
spatialmath-python        0.11               pyhd8ed1ab_0    conda-forge

**To Reproduce**
Example application of 'flip' to define a Denavit-Hartenberg joint in selfdefined NJ130.py.:
`RevoluteDH(
                a=400*mm,
                d=550*mm,
                alpha=-90*deg,
                offset= 0,
                qlim=np.array([-180*deg, 180*deg]),
                flip=True 
            ),`
 
Executed code:
`import roboticstoolbox as rtb`
`import numpy as np`
`robot =rtb.models.DH.NJ130()`
`T = robot.fkine(robot.qr)`
`robot.ikine_LM(T)`

Output:
`IKsolution(q=array([ 0.24198699, -0.30474617, -0.10311216,  0.81225038,  0.26067733,  0.74543783]), success=False, reason='rejected-step limit 100 exceeded', iterations=159, residual=0.36820261751840655)`

**Comment by jhavl** [comment]
Hi @jorks3z, this is a limitation of the current iksolvers we have in the toolbox, its failing to find a solution, not a bug in the code. We are surrently working on a new suite of IK solvers which may help with the robot.
