### ISSUE TITLE
Swift backend.step() crashes when updating ERobot state

### ISSUE THREAD

**Issue by MichaelRyanGreer** [petercorke/robotics-toolbox-python#276]
**Describe the bug**
Swift simulator crashes on step() call for ERobot constructed from URDF file. Swift runs, opens browser tab, and displays robot, but step() fails with output:

`AttributeError: 'ERobot' object has no attribute '_valid_qlim'`

ERobot does not explicitly have a _valid_qlim attribute, but BaseERobot does so it might be an issue with inheritance.

It's equally possible that there's a different pipeline to get a URDF rep into Swift; if that is the case please let me know.

**Version information**

roboticstoolbox-python 0.11.0 installed from pypi
swift-sim 0.10.0 installed from pypi
spatialmath-python 0.11 installed form pypi

**To Reproduce**

```
import roboticstoolbox as rtb

robot = rtb.robot.ERobot.URDF("robfile.xml")
print(robot)

from roboticstoolbox.backends.swift import Swift
backend = Swift()
backend.launch()
backend.add(robot)

backend.step()
```

URDF file used is attached as text file

**Expected behavior**
Swift should just update the state of the robot

**Environment (please complete the following information):**
Python 3.8
Kubuntu 20.04LTS
Google Chrome

**Additional context**
Full Error Output:

```
Traceback (most recent call last):
  File "simpleTest.py", line 11, in <module>
    backend.step()
  File "/usr/local/lib/python3.8/dist-packages/swift/Swift.py", line 204, in step
    self._step_robot(obj, dt, self.swift_options[i]["readonly"])
  File "/usr/local/lib/python3.8/dist-packages/swift/Swift.py", line 556, in _step_robot
    robot._n, robot._valid_qlim, dt, robot._q, robot._qd, robot._qlim
AttributeError: 'ERobot' object has no attribute '_valid_qlim'
```

[robfile.txt](https://github.com/petercorke/robotics-toolbox-python/files/7339402/robfile.txt)

Thanks for creating and maintaining such a great tool!

**Comment by jhavl** [comment]
Hey @MichaelRyanGreer, thanks for bringing this to our attention. This has been fixed on the future branch and will be incorporated into the next release.
