### ISSUE TITLE
Installation fails for Python3.9.7 as cannot build wheels for quadprog

### ISSUE THREAD

**Issue by ZhongmouLi** [petercorke/robotics-toolbox-python#277]
**Describe the bug**
Installation fails for Python3.9.7 as cannot build wheels for quadprog
using 
pip3 install  roboticstoolbox-python

**Screenshots**

![Screenshot from 2021-10-14 21-38-40](https://user-images.githubusercontent.com/21055404/137384649-0c643947-be92-44f1-8a89-aaccb8e5a84b.png)

![Screenshot from 2021-10-14 21-38-49](https://user-images.githubusercontent.com/21055404/137384684-6e6060d4-76c9-4134-b487-b064a6e2c00c.png)

![Screenshot from 2021-10-14 21-39-03](https://user-images.githubusercontent.com/21055404/137384705-a3f1f7b6-6c80-49e1-a917-ebdfd22557e6.png)

**Environment (please complete the following information):**
Ubuntu 18.04
Python 3.9.7

**Comment by pkoprov** [comment]
Almost the same for Windows 10
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel
Successfully installed wheel-0.37.1
PS D:\OneDrive - North Carolina State University\ECE 555 Computer Control of Robots\robotics-toolbox-python> pip install -e .
Obtaining file:///D:/OneDrive%20-%20North%20Carolina%20State%20University/ECE%20555%20Computer%20Control%20of%20Robots/robotics-toolbox-python
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.18.0 in c:\users\kopro\appdata\local\programs\python\python39\lib\site-packages (from roboticstoolbox-python==0.11.0) (1.21.3)

Collecting spatialmath-python>=0.11
  Using cached spatialmath-python-0.11.tar.gz (162 kB)
  Preparing metadata (setup.py) ... done
Collecting spatialgeometry>=0.2.0
  Using cached spatialgeometry-0.2.0-py3-none-any.whl (11 kB)
Collecting pgraph-python
  Using cached pgraph-python-0.6.1.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scipy in c:\users\kopro\appdata\local\programs\python\python39\lib\site-packages (from roboticstoolbox-python==0.11.0) (1.7.1)
Requirement already satisfied: matplotlib in c:\users\kopro\appdata\local\programs\python\python39\lib\site-packages (from roboticstoolbox-python==0.11.0) (3.4.3)
Collecting ansitable
  Using cached ansitable-0.9.6.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting swift-sim>=0.10.0
  Using cached swift_sim-0.10.0-cp39-cp39-win_amd64.whl (5.7 MB)
Collecting qpsolvers
  Using cached qpsolvers-1.8.0-py3-none-any.whl (36 kB)
Collecting rtb-data
  Using cached rtb_data-0.10.1-py3-none-any.whl (93.7 MB)
Collecting progress
  Using cached progress-1.6.tar.gz (7.8 kB)
  Preparing metadata (setup.py) ... done
Collecting colored
  Using cached colored-1.4.3.tar.gz (29 kB)
  Preparing metadata (setup.py) ... done
Collecting sphinxcontrib-jsmath
  Using cached sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Collecting websockets
  Using cached websockets-10.1-cp39-cp39-win_amd64.whl (97 kB)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\kopro\appdata\local\programs\python\python39\lib\site-packages (from matplotlib->roboticstoolbox-python==
0.11.0) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\kopro\appdata\local\programs\python\python39\lib\site-packages (from matplotlib->roboticstoolbox-python==0.11.
0) (0.11.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\kopro\appdata\local\programs\python\python39\lib\site-packages (from matplotlib->roboticstoolbox-pytho
n==0.11.0) (2.8.2)
Requirement already satisfied: pillow>=6.2.0 in c:\users\kopro\appdata\local\programs\python\python39\lib\site-packages (from matplotlib->roboticstoolbox-python==0.11
.0) (8.4.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\kopro\appdata\local\programs\python\python39\lib\site-packages (from matplotlib->roboticstoolbox-python==0
.11.0) (3.0.4)
Collecting quadprog>=0.1.8
  Using cached quadprog-0.1.11.tar.gz (121 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: six>=1.5 in c:\users\kopro\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.7->matplotlib->roboticstoo
lbox-python==0.11.0) (1.16.0)
Building wheels for collected packages: spatialmath-python, ansitable, pgraph-python, progress, quadprog, colored
  Building wheel for spatialmath-python (setup.py) ... done
  Created wheel for spatialmath-python: filename=spatialmath_python-0.11-py3-none-any.whl size=174332 sha256=c24f7288772eff8979e17f70524091c0097ad7d926cdeb4baa33b88ac
bafeb1d
  Stored in directory: c:\users\kopro\appdata\local\pip\cache\wheels\54\b4\89\bff29e319fec4762fb7ae238cfecda0b49fd337d9588a67c62
  Building wheel for ansitable (setup.py) ... done
  Created wheel for ansitable: filename=ansitable-0.9.6-py3-none-any.whl size=12621 sha256=d4e3f39575dea7b50e1d0a07f50ab2a3582813236a86beefa416093c66ef60f9
  Stored in directory: c:\users\kopro\appdata\local\pip\cache\wheels\ff\b8\23\38835f75c968916f64f47e2d8ce524d394db2a84dcd3570b72
  Building wheel for pgraph-python (setup.py) ... done
  Created wheel for pgraph-python: filename=pgraph_python-0.6.1-py3-none-any.whl size=11482 sha256=6d5b414ce6e7da25f5fbea3fa9a887aed0a4c51f66b87eb35a6f27f1df877cea
  Stored in directory: c:\users\kopro\appdata\local\pip\cache\wheels\72\eb\bd\6b7321966c00d687ba6778fdebf035718597878f4e2333c074
  Building wheel for progress (setup.py) ... done
  Created wheel for progress: filename=progress-1.6-py3-none-any.whl size=9632 sha256=7347a023103a876dd0118bf7913a469c4dc4a14c28e02e2b951364c612e7b171
  Stored in directory: c:\users\kopro\appdata\local\pip\cache\wheels\4c\9b\0a\a78ff56725af3ef70792f9ed0f8dbbc4c0315edc62cbc4a6b8
  Building wheel for quadprog (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for quadprog (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'quadprog' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for quadprog
  Building wheel for colored (setup.py) ... done
  Created wheel for colored: filename=colored-1.4.3-py3-none-any.whl size=14342 sha256=dd017a2ac21589eefecfcac828c2fc658218d3e0a546b133f6032f079570c026
  Stored in directory: c:\users\kopro\appdata\local\pip\cache\wheels\31\7b\79\7cf37e7860649bd09d359bfbbde9084a103a35eedd8f12a592
Successfully built spatialmath-python ansitable pgraph-python progress colored
Failed to build quadprog
ERROR: Could not build wheels for quadprog, which is required to install pyproject.toml-based projects

**Comment by Drewsername** [comment]
Had this issue for ubuntu 18.04, python 3.8.0, turns out python3-dev package was missing.
I resolved this with `sudo apt-get install -y libpython3.8-dev` so perhaps `sudo apt-get install -y libpython3.9-dev` would resolve this issue for you.

**Comment by jhavl** [comment]
This has been fixed on the future branch and will be incorporated into the next realease. We used to have a dependancy on Quadprog which requires a C++ compiler to build the package. This can be fixed with using @Drewsername solution on Ubuntu or https://visualstudio.microsoft.com/visual-cpp-build-tools/ on Windows.
