### ISSUE TITLE
Scene is not showing

### ISSUE THREAD

**Issue by ReDHaWk6520** [petercorke/robotics-toolbox-python#284]
**Check here first**

[Common issues](https://github.com/petercorke/robotics-toolbox-python/wiki/Common-Issues)

**Describe the bug**
I was trying to plot the trajectory of my robot arm. Everything works but the scene which uses matplot is not showing up.

**Version information**

Installed from PyPI. Python 3.9.7

**To Reproduce**
%matplotlib notebook
import roboticstoolbox as rtb
p560=rtb.models.DH.Puma560()
qt=rtb.tools.trajectory.jtraj(p560.qz,p560.qr,50)
p560.plot(qt.q)

**Expected behavior**
Code is working but no trajectory video or gif is not showing

**Screenshots**

**Environment (please complete the following information):**
 Windows, Visual Studio code

**Additional context**

**Comment by jhavl** [comment]
Hey @ReDHaWk6520, your code also works for me. I suspect your issue is the Jupyter notebook. Try running it from a file or command line.
