### ISSUE TITLE
Panda arm fkine simulation

### ISSUE THREAD

**Issue by hibabfht** [petercorke/robotics-toolbox-python#285]
**Describe the bug**
The arm do not converge to the desired point or stay fixed in undesired position, depend on the final position coordinates.

**Version information**

Did you install from PyPI
pip version 21.2.4
I installed also swift, sympy, spatialmath-python manually.

**To Reproduce**
import roboticstoolbox as rtb
import swift
import spatialmath as sm
import spatialgeometry as sg
import numpy as np

env = swift.Swift()
env.launch(realtime = True)

robot = rtb.models.Panda()
robot.q = robot.qr # La position initiale

env.add(robot, robot_alpha = 0.5, collision_alpha = 0.3)

Pos_fin = robot.fkine(robot.q) * sm.SE3.Tx(0.2) * sm.SE3.Ty(0.2) * sm.SE3.Tz(0) # La position désirée

axes = sg.Axes(length = 0.1, base = Pos_fin)
env.add(axes)

arrived = False
while not arrived :
    V, arrived = rtb.p_servo(robot.fkine(robot.q), Pos_fin, gain = 0.1, threshold = 0.01)
    J = robot.jacobe(robot.q)
    robot.q = np.linalg.pinv(J) @ V
    env.step(0.01)
env.hold()

**Expected behavior**
The arm move on progressively to reach the final position Pos_fin.

**Screenshots**
![image](https://user-images.githubusercontent.com/61683358/147616184-adbe8e34-64c3-4eb4-9d9d-39016551b542.png)
For those Pos_fin coordinates, the model is fixed at this weird position.

**Environment (please complete the following information):**
- Windows 10
- Python 3.9.8 64-bits
- Browser Mozilla Firefox

**Additional context**
/

**Comment by jhavl** [comment]
Hey @hibabfht, you need to set the joint velocities with `qd`. not the joint positions `q` in the for loop.

Here is the fixed code:

```
import roboticstoolbox as rtb
import swift
import spatialmath as sm
import spatialgeometry as sg
import numpy as np

env = swift.Swift()
env.launch(realtime=True)

robot = rtb.models.Panda()
robot.q = robot.qr  # La position initiale

env.add(robot, robot_alpha=0.5, collision_alpha=0.3)

Pos_fin = (
    robot.fkine(robot.q) * sm.SE3.Tx(0.2) * sm.SE3.Ty(0.2) * sm.SE3.Tz(0)
)  # La position désirée

axes = sg.Axes(length=0.1, pose=Pos_fin)
env.add(axes)

arrived = False
while not arrived:
    V, arrived = rtb.p_servo(robot.fkine(robot.q), Pos_fin, gain=0.1, threshold=0.01)
    J = robot.jacobe(robot.q)

    robot.qd = np.linalg.pinv(J) @ V
    env.step(0.01)

env.hold()
```

The key fix is `robot.qd = np.linalg.pinv(J) @ V`
