### ISSUE TITLE
Function "jacobm" doesn't work

### ISSUE THREAD

**Issue by vog55** [petercorke/robotics-toolbox-python#288]
Hello, 

I have a problem with the subfunction "jacobm". According to your paper "Position-Based Servoing Example on an omnidirectional mobile manipulator" you use the subfunction "jacobm" for the linear component of objective function. To understand the sense/purpose of the subfunction, I broke down their source code. In doing so, I constantly get the following error when executing the "jacobm" (see png file). I can't quite understand this, since it is not a singularity. 

<img width="1033" alt="Bildschirmfoto 2022-01-07 um 11 21 59" src="https://user-images.githubusercontent.com/95863158/148529849-fb22afea-b62b-4acd-83c5-895bc44ae6a8.png">

**Comment by petercorke** [comment]
Not sure I ever wrote the paper you mention.

`jacobm` is the Jacobian of the manipulator manipulability function, which doesn't seem relevant to visual servoing or omnidirectional mobile platforms.

**Comment by jhavl** [comment]
Hey @vog55 ,
To assist further, can you please provide the code for how you got this error to reproduce?

**Comment by jhavl** [comment]
The jacobm function is working fine on the future branch with

```
import roboticstoolbox as rtb

panda = rtb.models.Panda()
panda.q = panda.qr
print(panda.jacobm(panda.q))
```
