### ISSUE TITLE
Robot autoscale fails

### ISSUE THREAD

**Issue by Jakubach** [petercorke/robotics-toolbox-python#295]
Hello, running the below example:
```
robot = rtb.models.DH.Puma560()
robot.plot(robot.qn, block=True)
```
give me a plot like this:
![Robotics_Toolbox_for_Python_(Figure_1)](https://user-images.githubusercontent.com/29859041/154071942-5bfe2785-265a-4dc1-ada9-82a2f12d375b.png)

There is something wrong with scaling. The same issue I got with ```teach``` command.
I manage to add scaling by hand, for example:
`robot.plot(robot.qn, block=True,limits = [-1,1,-1,1,-1,1])`

I work on Windows 11, with Python 3.8 and I was using the latest snapshot installed with:
`pip3 install roboticstoolbox-python[vpython] sympy`

**Comment by jhavl** [comment]
Hey Jakubach, autoscaling in 3D is currently not directly supported by Matplotlib in the same way they do for 2D. 

We use the following function to attempt autoscaling:

```
def _set_axes_equal(self):
    """
    Make axes of 3D plot have equal scale so that spheres appear as
    spheres, cubes as cubes, etc..  This is one possible solution to
    Matplotlib's ax.set_aspect('equal') and ax.axis('equal') not
    working for 3D.
    
    """
    
    if self.limits is not None:
        return
    
    self.ax.autoscale(enable=True, axis="both", tight=False)
    
    x_limits = self.ax.get_xlim3d()
    y_limits = self.ax.get_ylim3d()
    z_limits = self.ax.get_zlim3d()
    
    x_range = abs(x_limits[1] - x_limits[0])
    x_middle = np.mean(x_limits)
    y_range = abs(y_limits[1] - y_limits[0])
    y_middle = np.mean(y_limits)
    z_range = abs(z_limits[1] - z_limits[0])
    z_middle = np.mean(z_limits)
    
    # The plot bounding box is a sphere in the sense of the infinity
    # norm, hence I call half the max range the plot radius.
    plot_radius = 0.5 * max([x_range, y_range, z_range])
    
    self.ax.set_xlim3d([x_middle - plot_radius, x_middle + plot_radius])
    self.ax.set_ylim3d([y_middle - plot_radius, y_middle + plot_radius])
    self.ax.set_zlim3d([z_middle - plot_radius, z_middle + plot_radius])
```
But it doesn't seem to be reliable on every platform/matplotlib verion or backend. 

![plot](https://user-images.githubusercontent.com/21215791/162118629-f308adab-5dd1-4604-8e90-6c739df68c95.png)

As you can see, it works fine on my machine. If you have any ideas for how this can be fixed feel free to add a pull request.
