### ISSUE TITLE
Miss update of jacob0 in inertia_x, coriolis_x and gravload_x 

### ISSUE THREAD

**Issue by Betancourt20** [petercorke/robotics-toolbox-python#301]
Hello,
I am using the the Github version `2.25.1` and I had a few errors when traying to obtain 
```
robot.inertia_x(robot.q)
robot.coriolis_x(robot.q)
robot.gravload_x(robot.q)
```
and got the error
```
Ja = self.jacob0(q[0, :], analytical=analytical)
NameError: name 'analytical' is not defined
```
Therefore, I just delete this extra phrase `` analytical=analytical`` from the `Dynamics.py` file in the following lines : ``1118``,``1132``, ``1025``, ``1008``. Also update the jacob0 function in the inertial_x function (lines `907` and `920`).
Best regards,

Julio

**Comment by jhavl** [comment]
Your particular issue has been fixed but there is still a larger issue revolving around static joints within rne, see #236
