### ISSUE TITLE
Python 3.10 is not in the test matrix

### ISSUE THREAD

**Issue by tdamsma** [petercorke/robotics-toolbox-python#307]
Would you accet PR's adding python 3.10 to the test build matrix? Also, as the matrix is kind of large with currently 9 runs, perhaps an idea to prune some versions, for example only keep oldest and newest supported versions [3.7, 3.10]

**Comment by jhavl** [comment]
Hey @tdamsma, we are happy to do the 9-12 runs of tests as it very occasionally picks up unique issues. I have recently added 3.10 but if I miss 3.11 in a few months feel free to add a PR :)
