### ISSUE TITLE
Puma560 has no `printdyn` attribute

### ISSUE THREAD

**Issue by walchko** [petercorke/robotics-toolbox-python#309]
When I run this example, it fails with the following error:

https://github.com/petercorke/robotics-toolbox-python/blob/176f21cd8e7611c74b3346ccfd5fce470f6ec487/roboticstoolbox/examples/puma_fdyn.py#L10

```python
Traceback (most recent call last):
  File "/Users/kevin/tmp/robottoolkit/./test.py", line 41, in <module>
    p560.printdyn()
AttributeError: 'Puma560' object has no attribute 'printdyn'
```

**Comment by petercorke** [comment]
Thanks @walchko, the example has been updated, that function is now called `dynamics`.
