### ISSUE TITLE
ROS2 Support

### ISSUE THREAD

**Issue by prasuchit** [petercorke/robotics-toolbox-python#332]
Hi,

It would be an extremely useful feature if we could talk to ROS2 through this library. The path planners in Moveit2 have many issues and this toolbox interfaced with ROS2 would compliment each other well.

Is there any plan to bring in ROS support soon? Thanks in advance.

**Comment by jhavl** [comment]
Hey @prasuchit, there is nothing stopping the toolbox from being used with ROS or ROS2. Simply `import roboticstoolbox` in a Python ROS node as you would any other Python package such as `numpy`, `scipy`, `opencv`, `matplotlib` etc.
