### ISSUE TITLE
Error while using ikine_LM 

### ISSUE THREAD

**Issue by razoentaki** [petercorke/robotics-toolbox-python#335]
I tried to give a target position which is out of the reach of robot Cobra600 to the ikine_LM function.
However, the result show it is success = True. How to make the success of ikine_LM function return False if the target position is out of reach??

`Cobra600 = rtb.models.DH.Cobra600()
print(Cobra600)
qe = [10,10,10,10]
T = Cobra600.fkine(qe) 
sol = Cobra600.ikine_LM(T)
print(sol)
Cobra600.plot(sol.q, block=True)`

`IKsolution(q=array([ 1.69963067,  2.56637061, 10.        ,  0.54918659]), success=True, reason=None, iterations=12, residual=1.8233519592079866e-11)`

Another problem is when i use the mask parameter in ikine_LM function. I always get this error. 
`sol = Cobra600.ikine_LM(T, mask=[0,1,1,0,0,0])
`
How to solve this error??
`Traceback (most recent call last):
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix`

**Comment by petercorke** [comment]
There are a few things going on here.  Firstly, I get different results to you

```
>>> qe = [10,10,10,10]
[10, 10, 10, 10]

>>> T = Cobra600.fkine(qe)
  -0.8391   -0.544     0        -0.1605    
  -0.544     0.8391    0         0.07425   
   0         0        -1        -9.613     
   0         0         0         1         


>>> sol = Cobra600.ikine_LM(T)
IKSolution(q=array([  0.8471, -0.02044,    9.928,    -2.92]), success=False, iterations=3000, searches=100, residual=0.2894343927639082, reason='iteration and search limit reached')
```

Secondly, this is an odd way to get an out of reach pose.  Three elements of `qe` are angles, and you've requested 10 radians which makes it hard to figure if they are out of bounds, since the bounds are in degrees.
