### ISSUE TITLE
How to fix an eye-in-hand camera frame through rtb.DHRobot?

### ISSUE THREAD

**Issue by River-mao** [petercorke/robotics-toolbox-python#337]
I have created a custom robot class according to my own DH params. I want to simulate a frame transformation between camera frame and end-effector frame, but I don't find some related information that describe how to fix an eye-in-hand camera frame in the 6th link of robot. I need some help. Thanks a lot.

**Comment by petercorke** [comment]
You can either set some of the DH params for the last link, but that's not very general, or add a tool transform to the robot

**Comment by River-mao** [comment]
> 
Thanks a lot， I solve this by adding a tool transformation with SE3 apart from the robot definition, which is more convenient.

**Comment by petercorke** [comment]
good news, I'll close this now
