### ISSUE TITLE
Tool transformation not plotted

### ISSUE THREAD

**Issue by eliaslochner** [petercorke/robotics-toolbox-python#344]
**Check here first**

[Common issues](https://github.com/petercorke/robotics-toolbox-python/wiki/Common-Issues)

**Describe the bug**
When creating a DH robot model with a tool transformation like e.g. the Panda robot, the tool transformation is not considered in the print command or the plot command.

**Version information**
Installed version 1.0.3 using PyPi

**To Reproduce**
```
import roboticstoolbox as rtb

panda = rtb.models.DH.Panda()
print(panda)
panda.plot(panda.qr)
```

**Expected behavior**
```
┌─────┬──────┐
│tool │ The transformation... │
└─────┴──────┘
```

The plot shows the actual TCP coordinate system

**Screenshots**
```
DHRobot: Panda (by Franka Emika), 7 joints (RRRRRRR), dynamics, geometry, modified DH parameters
┌────────┬────────┬─────┬───────┬─────────┬────────┐
│ aⱼ₋₁   │  ⍺ⱼ₋₁  │ θⱼ  │  dⱼ   │   q⁻    │   q⁺   │
├────────┼────────┼─────┼───────┼─────────┼────────┤
│    0.0 │   0.0° │  q1 │ 0.333 │ -166.0° │ 166.0° │
│    0.0 │ -90.0° │  q2 │   0.0 │ -101.0° │ 101.0° │
│    0.0 │  90.0° │  q3 │ 0.316 │ -166.0° │ 166.0° │
│ 0.0825 │  90.0° │  q4 │   0.0 │ -176.0° │  -4.0° │
│-0.0825 │ -90.0° │  q5 │ 0.384 │ -166.0° │ 166.0° │
│    0.0 │  90.0° │  q6 │   0.0 │   -1.0° │ 215.0° │
│  0.088 │  90.0° │  q7 │ 0.107 │ -166.0° │ 166.0° │
└────────┴────────┴─────┴───────┴─────────┴────────┘
┌─────┬──────┐
│tool │ None │
└─────┴──────┘
┌─────┬─────┬────────┬─────┬───────┬─────┬───────┬──────┐
│name │ q0  │ q1     │ q2  │ q3    │ q4  │ q5    │ q6   │
├─────┼─────┼────────┼─────┼───────┼─────┼───────┼──────┤
│  qr │  0° │ -17.2° │  0° │ -126° │  0° │  115° │  45° │
│  qz │  0° │  0°    │  0° │  0°   │  0° │  0°   │  0°  │
└─────┴─────┴────────┴─────┴───────┴─────┴───────┴──────┘
```
![image](https://user-images.githubusercontent.com/107397470/212716154-75d8da92-16c9-4829-8709-d1a2a0984e25.png)
The TCP is at the last joint coordinate system instead.

**Environment (please complete the following information):**
 - Your OS: Linux
- Your Python version: 3.8

**Comment by petercorke** [comment]
Hi @eliaslochner thanks for pointing these out.  There were a couple of bugs involved, fixed now on future branch and will be included in the next release.
