### ISSUE TITLE
Set joint limits (qlim) for individual robot after creating

### ISSUE THREAD

**Issue by slyandsmart** [petercorke/robotics-toolbox-python#355]
**Describe the bug**
Joint limits can not be set after creation of a robot model. 
**Version information**

Did you install from PyPI or GitHub?
PyPI version 1.0.3

**To Reproduce**
The shortest, complete, Python script that exhibits the bug.
`import numpy as np`
`import roboticstoolbox as rtb`
`robot = rtb.DHRobot(`
    `[rtb.RevoluteDH(alpha=np.pi/2,qlim=[0,np.pi]),`
     `rtb.RevoluteDH(a=0.4318),`
     `rtb.RevoluteDH(d=0.15005, a=0.0203, alpha=-np.pi/2),`
     `rtb.RevoluteDH(d=0.4318, alpha=np.pi/2),`
     `rtb.RevoluteDH(alpha=-np.pi/2),`
     `rtb.RevoluteDH()], name="Puma560")`

`puma = rtb.models.DH.Puma560()`
`print('robot q lim:\n',robot.qlim)`
`print('puma q lim:\n', puma.qlim)`
`robot.qlim = [[0,0,0,0,0,0],[1,1,1,1,1,1]]`

The script output, including error messages.
`robot.qlim = [[0,0,0,0,0,0],[1,1,1,1,1,1]]`
`Traceback (most recent call last):`
 `File "C:\Users\c8501077\AppData\Local\Temp\ipykernel_21840\1339630953.py", line 1, in <cell line: 1>`
  `robot.qlim = [[0,0,0,0,0,0],[1,1,1,1,1,1]]`
`AttributeError: can't set attribute`

**Expected behavior**
Individual joint limits should be set to a new value. 

**Environment (please complete the following information):**
 - Windows 10, Anaconda 
 - Pyton version3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:45) [MSC v.1929 64 bit (AMD64)]
 - IPython 7.33.0
 - Spyder 5.3.1

**Comment by jhavl** [comment]
Hey @slyandsmart, thanks for bringing this to our attention, I'll get this incorporated in the next release.
