### ISSUE TITLE
The Axes in PDF is different with the axes in dk-tutorial's picture

### ISSUE THREAD

**Issue by hengyue-dunhuang** [petercorke/robotics-toolbox-python#357]
[Common issues](https://github.com/petercorke/robotics-toolbox-python/wiki/Common-Issues)

The Axes in PDF is different with the axes in dk-tutorial's picture,which botherd me a lot. I think that the axes in dk-turtorial is right.

**Screenshots**
dk-tutorial:
![image](https://user-images.githubusercontent.com/77217960/224868826-4e789f60-d44b-4935-b08b-b44c6ba2c73d.png)

your kinematics pdf:
![image](https://user-images.githubusercontent.com/77217960/224868898-d8d29354-dbed-4ed9-8b3d-671b50efd3be.png)

**Comment by jhavl** [comment]
Hey @hengyue-dunhuang, thanks for bringing this up. This issue should be posted on the dkt repository though (https://github.com/jhavl/dkt/). The Arxiv pdf will be updated shortly.
