### ISSUE TITLE
Acceleration-based mobile robot model

### ISSUE THREAD

**Issue by JakobThumm** [petercorke/robotics-toolbox-python#359]
I would like to use a mobile robot model that acts on the acceleration instead of the velocity.
Is that currently possible?
If not would that be easy to implement?
I mainly would like to use the trajectory planner to plan a trajectory from the current state to a given state.

**Comment by petercorke** [comment]
At the moment there is no ability to do this.  Linear and angular acceleration?  You could simply add an integrator between your controller and the velocity-input vehicle model.
