### ISSUE TITLE
bug in ERobot.py:hierarchy()

### ISSUE THREAD

**Issue by MiaoDragon** [petercorke/robotics-toolbox-python#362]
**Describe the bug**
in hierarchy() function, the line
`for child in link.child:`
should be
`for child in link.children:`

**Version information**

Did you install from PyPI or GitHub? Y
If PyPI what version number? 1.0.3
If GitHub what commit hash? master branch

**Comment by jhavl** [comment]
Hey @MiaoDragon, this has been fixed on the future branch and will be included in the next release
