### ISSUE TITLE
ik_lm_chan

### ISSUE THREAD

**Issue by jianchaoci** [petercorke/robotics-toolbox-python#370]
**Check here first**

[Common issues](https://github.com/petercorke/robotics-toolbox-python/wiki/Common-Issues)

**Describe the bug**

**Version information**

Did you install from PyPI or GitHub?
PyPI
If PyPI what version number?
1.0.3

**To Reproduce**
robot = rtb.models.Panda()
Te = robot.fkine(robot.qr)  # forward kinematics
Tep = SE3.Trans(0.6, -0.3, 0.1) * SE3.OA([0, 1, 0], [0, 0, -1])
sol = robot.ik_lm_chan(Tep)

2. AttributeError: 'Panda' object has no attribute 'ik_lm_chan'

**Expected behavior**

**Environment (please complete the following information):**
 - Linux 20.04.
- Python=3.8

**Additional context**

**Comment by jhavl** [comment]
Hey @jianchaoci, are you definitely using version 1.0.3? We just updated the API in v1.1.0 so ik_lm_chan is now ik_LM

**Comment by jianchaoci** [comment]
> ?

Hi, yes you are correct, The version I used is v1.1.0. I checked once the version is 1.0.3. Then I re-installed it but forget to check the version again. Thanks for your reply.
