### ISSUE TITLE
Automatic differentiation capabilities

### ISSUE THREAD

**Issue by joao-pm-santos96** [petercorke/robotics-toolbox-python#373]
Hi!
Thank you for the great package!! One question: are you planning to integrate any kind of automatic differentiation capabilities? For example, with [JAX](https://github.com/google/jax)?

Thank you!

**Comment by jhavl** [comment]
HEy @joao-pm-santos96, thanks for using the toolbox! It's not in our plans but the toolbox is pretty extensible so you could have a crack yourself
