### ISSUE TITLE
How to change joint limits?

### ISSUE THREAD

**Issue by jianchaoci** [petercorke/robotics-toolbox-python#374]
Hi, 
Thanks for the great work. Recently I am using this robotic-toolbox combined with Webots to do some simulation work. The robot I am using is a UR5, it is set on a table. To avoid the robot touch the table, I want to add some limits to the joints, and therefore the solutions that violate the limits will be rejected. Could you give any suggestions on how to do that?

**Comment by jhavl** [comment]
Hi @jianchaoci, just restricting joint limits is insufficient for this task, you need to limit the cartesian position of the end-effector. In simple terms, calculate the forward kinematics (using the `fkine` method of the robot object) and see if this is outside of your safe bounds.
