### ISSUE TITLE
Cannot add .OBJ files to Swift

### ISSUE THREAD

**Issue by joao-pm-santos96** [petercorke/robotics-toolbox-python#380]
**Describe the bug**
I can create a spatialgeometry.Mesh object in which the input is an .obj file. But, when I try to add this Mesh to Swift I receive the message (in the web browser) "An unexpected error has occurred."

**Version information**

Installed from PyPi, version 1.0.6

**To Reproduce**
1. Create a Mesh object from a .obj file
2. Add it to a Swift environment

**Expected behavior**
I should be able to see the mesh I've loaded

**Comment by jhavl** [comment]
Hi @joao-pm-santos96, can you please add this issue to the swift repository https://github.com/jhavl/swift
